# Generated by Django 4.0.6 on 2022-07-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='elamir', max_length=100),
            preserve_default=False,
        ),
    ]
