# Generated by Django 4.0.6 on 2022-07-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_skill_skillitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillitem',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='skillitem',
            name='username',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillItem',
        ),
    ]
